name: BuildPlugin

on:
    push:
        branches:
            - master

jobs:
    build:
        uses: FriendsOfShopware/workflows/.github/workflows/store.yml@main
        with:
            extensionName: FroshProductCompare
            shopwareVersion: 6.4.1
        secrets:
            accountUser: ${{ secrets.ACCOUNT_USER }}
            accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}
