name: BuildPlugin

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    build:
        uses: FriendsOfShopware/workflows/.github/workflows/store-shopware-cli.yml@main
        with:
            extensionName: FroshProductCompare
        secrets:
            accountUser: ${{ secrets.ACCOUNT_USER }}
            accountPassword: ${{ secrets.ACCOUNT_PASSWORD }}
            ghToken: ${{ secrets.GITHUB_TOKEN }}
