name: StoreCheck
on:
    push:
        branches:
            - master
        tags:
            - '*'

env:
    PLUGIN_NAME: FroshProductCompare
    ACCOUNT_USER: ${{ secrets.ACCOUNT_USER }}
    ACCOUNT_PASSWORD: ${{ secrets.ACCOUNT_PASSWORD }}
    PLUGIN_UPLOADER_VERSION: 0.3.2

jobs:
    validatePlugin:
        if: startsWith(github.ref, 'refs/tags/') != true
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: Build Zip
                run: php frosh-plugin-upload.phar ext:zip ${PLUGIN_NAME}

            -   name: Validate Zip
                run: php frosh-plugin-upload.phar ext:validate $(pwd)/${PLUGIN_NAME}*.zip

    StoreUpdate:
        needs: validatePlugin
        if: startsWith(github.ref, 'refs/tags/') != true
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: StoreUpdate
                run: php frosh-plugin-upload.phar ext:update $(pwd)/${{ env.PLUGIN_NAME }}/

    StoreRelease:
        if: startsWith(github.ref, 'refs/tags/')
        runs-on: ubuntu-latest
        steps:
            -   name: Get the version
                id: get_version
                run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

            -   name: Checkout
                uses: actions/checkout@v2.3.1
                with:
                    path: ${{ env.PLUGIN_NAME }}

            -   name: getPluginUploader
                run: wget 'https://github.com/FriendsOfShopware/FroshPluginUploader/releases/download/${{ env.PLUGIN_UPLOADER_VERSION }}/frosh-plugin-upload.phar' -O frosh-plugin-upload.phar

            -   name: Build Zip
                run: php frosh-plugin-upload.phar ext:zip ${PLUGIN_NAME}

            -   name: StoreUpload
                run: php frosh-plugin-upload.phar ext:upload $(pwd)/${PLUGIN_NAME}*.zip

            -   name: Create Release
                id: create_release
                uses: actions/create-release@v1.0.0
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    tag_name: ${{ steps.get_version.outputs.VERSION }}
                    release_name: ${{ steps.get_version.outputs.VERSION }}
                    draft: false
                    prerelease: false

            -   name: Upload Release Asset
                id: upload_release_asset
                uses: actions/upload-release-asset@v1.0.2
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                with:
                    upload_url: ${{ steps.create_release.outputs.upload_url }}
                    asset_path: ${{ github.workspace }}/${{ env.PLUGIN_NAME }}-${{ steps.get_version.outputs.VERSION }}.zip
                    asset_name: ${{ env.PLUGIN_NAME }}.zip
                    asset_content_type: application/zip
